#+LANGUAGE: ru
#+AUTHOR: Krutko Nikita / KrutNA
#+OPTIONS: toc:nil
#+LATEX: \large
#+LATEX: \thispagestyle{empty}
#+LATEX_HEADER: \usepackage{makecell}
#+BEGIN_CENTER
*Санкт-Петербургский Национальный Исследовательский*\\
*Университет Информационных Технологий, Механики и Оптики*\\
*Факультет Программной Инженерии и Компьютерной Техники*\\
#+END_CENTER
#+LATEX: \vspace{1em}
#+ATTR_LATEX: :width 120px
#+ATTR_ORG: :width 120px
file:../itmo-logo.png
#+LATEX: \LARGE
#+LATEX: \vspace{5em}
#+BEGIN_CENTER
*Вариант №27*\\
*Лабораторная работа №1*\\
#+LATEX: \Large
*по дисциплине*\\
#+LATEX: \LARGE
*/'Информатика'/*\\
#+END_CENTER
#+LATEX: \vspace{11em}
#+LATEX: \large
#+LATEX: \begin{flushright}
*Выполнил:*\\
*Студент группы P3113*\\
*/Крутько Никита;/ : 242570*\\
*Преподаватель:*\\
*/Малышева Татьяна Алексеевна/*\\
#+LATEX: \end{flushright}
#+LATEX: \vspace{4em}
#+LATEX: \large
#+BEGIN_CENTER
*Санкт-Петербург 2019 г.*
#+END_CENTER
#+LATEX: \pagebreak{}
#+TOC: headlines 2
#+LATEX: \pagebreak{}
** Описание
*** Задание
Перевести число "А", заданное в системе счисления "В", в систему счисления "С". Числа "А", "В" и "С" взять из представленных ниже таблиц. Вариант выбирается как сумма последнего числа в номере группы и номера в списке группы согласно ISU. Т.е. 13-му человеку из группы P3102 соответствует 15-й вариант (=2 + 13).
*** Правила
Всего нужно решить 11 примеров. Для примеров с 5-го по 7-й выполнить операцию перевода по сокращенному правилу (для систем с основанием 2 в системы с основанием 2^k). Для примеров с 4-го по 6-й и с 8-го по 9-й найти ответ с точностью до 5 знака после запятой. В примере 11 группа символов $\overline{1}$ означает -1 в симметричной системе счисления
** Задание 1
*** Задание:
|---+----+-------+----+---|
| # | #  | A     |  B | C |
| / | <> | <     |    | > |
|---+----+-------+----+---|
| # | 27 | 25307 | 10 | 9 |
|---+----+-------+----+---|

*** Решение
Найти: 25307_{10} = ?_9 \\
#+BEGIN_center
$\arraycolsep=0.05em
\begin{array}{rrrrr@{\,}r|rrrr@{\,}r|rrr@{\,}r|rr@{\,}r|r}
2 & 5 & 3 & 0 & 7 &&\, 9 \\
\cline{7-10}
1 & 8 &&&& &        \, 2 & 8 & 1 & 1 &&\, 9\\
\cline{1-3}\cline{12-15}
&   7 & 3 &&&&         2 & 7 &&&&      \, 3 & 1 & 2 &&\, 9\\
\cline{7-9}\cline{16-16}
&   7 & 2 &&&&&            1 & 1 &&&      2 & 7 &&&   \, 3 & 4 &&\, 9\\
\cline{2-4}\cline{12-14}\cline{18-19}
&&      1 & 0 &&&&&            9 &&&&         4 & 2 &&   2 & 7 &&\, \textbf{3}\\
\cline{8-10}\cline{16-17}
&&&         9 &&&&&            2 & 1 &&&      3 & 6 &&&\textbf{7}\\
\cline{3-5}\cline{13-14}
&&&         1 & 7 &&&&         1 & 8 &&&& \textbf{6}\\
\cline{9-10}
&&&&            9 &&&&&    \textbf{3}\\
\cline{4-5}
&&&&    \textbf{8}\\
\end{array}$
#+END_center

Из чего получаем, что: 25307_{10} = *37638_9*

** Задание 2
*** Задание
|---+----+-------+---+----|
| # | #  | A     | B | C  |
| / | <> | <     |   | >  |
|---+----+-------+---+----|
| # | 27 | 10053 | 7 | 10 |
|---+----+-------+---+----|

*** Решение
Найти: 10053_7 = ?_{10} \\
$\overset{4}{1}\overset{3}{0}\overset{2}{0}\overset{1}{5}\overset{0}{7}_7 =
1 * 7^4 + 0 * 7^3 + 0 * 7^2 + 5 * 7^1 + 7 * 7^0 =
2401 + 0 + 0 + 35 + 3 =
2439_{10}$
Из чего получаем, что: 10053_7 = *2439_{10}*

** Задание 3
*** Задание
|---+----+-------+----+---|
| # | #  | A     |  B | C |
| / | <> | <     |    | > |
|---+----+-------+----+---|
| # | 27 | 28D10 | 15 | 5 |
|---+----+-------+----+---|

*** Решение
Найти: 28D10_{15} = ?_5 \\ 
$\overset{4}{2}\overset{3}{8}\overset{2}{D}\overset{1}{1}\overset{0}{0}_{15} = 
2 * 15^4 + 8 * 15^3 + 13 * 15^2 + 1 * 15^1 + 0 * 15^0 =
101250 + 27000 + 2925 + 15 + 0 =
131190_{10}$ 
#+BEGIN_center
$\arraycolsep=0.05em
\begin{array}{rrrrrr@{\,}r|rrrrr@{\,}r|rrrr@{\,}r|rrrr@{\,}r|rrr@{\,}r|rr@{\,}r|r@{\,}r|r@{\,}r|r}
1 & 3 & 1 & 1 & 9 & 0 &&\, 5 \\
\cline{8-12}
1 & 0 &&&&&&            \, 2 & 6 & 2 & 3 & 8 &&\, 5 \\
\cline{1-3}\cline{14-17}
&   3 & 1 &&&&&            2 & 5 &&&&&         \, 5 & 2 & 4 & 7 &&\, 5 \\
\cline{8-10}\cline{19-23}
&   3 & 0 &&&&&&               1 & 2 &&&&         5 &&&&&         \, 1 & 0 & 4 & 9 &&\, 5 \\
\cline{2-4}\cline{14-16}\cline{24-26}
&&      1 & 1 &&&&&            1 & 0  &&&&&           2 & 4 &&&      1 & 0 &&&&      \, 2 & 0 & 9 &&\, 5 \\
\cline{9-11}\cline{19-22}\cline{28-29}
&&      1 & 0 &&&&&&               2 & 3 &&&&         2 & 0 &&&&&            4 & 9 &&   2 & 0 &&&   \, 4 & 1 &&\, 5 \\
\cline{3-5}\cline{15-17}\cline{24-26}\cline{31-31}
&&&         1 & 9 &&&&&            2 & 0 &&&&&            4 & 7 &&&&         4 & 9 &&&&         9 &&\, 4 & 0 &&\, 8 &&\, 5 \\
\cline{10-12}\cline{21-22}\cline{28-29}\cline{33-33}
&&&         1 & 5 &&&&&&               3 & 8 &&&&         4 & 5 &&&&&    \textbf{4} &&&&        5 &&&\textbf{1}&& 5 &&\, \textbf{1} \\
\cline{4-6}\cline{16-17}\cline{26-26}\cline{31-31}
&&&&            4 & 0 &&&&&            3 & 5 &&&&&    \textbf{2} &&&&&&&&&              \textbf{4} &&&&&      \textbf{3} \\
\cline{11-12}
&&&&            4 & 0 &&&&&&       \textbf{3}\\
\cline{5-7}
&&&&&       \textbf{0} 
\end{array}$
#+END_center
Из чего получаем, что 28D10_{15} = *1344230_5*

** Задание 4
*** Задание
|---+----+-------+----+---|
| # | #  | A     |  B | C |
| / | <> | <     |    | > |
|---+----+-------+----+---|
| # | 27 | 52.16 | 10 | 2 |
|---+----+-------+----+---|

*** Решение
Найти: 52.16_{10} = ?_{2}
#+BEGIN_center
\begin{tabular}{ p{200pt} p{200pt} }
\makecell{
$\arraycolsep=0.05em
\begin{array}{rr@{\,}r|rr@{\,}r|rr@{\,}r|r@{\,}r|r@{\,}r|r}
5 & 2 &&\, 2 \\
\cline{4-5}
5 & 2 &&\, 2 & 6 &&\, 2 \\
\cline{1-2}\cline{7-8}
&\textbf{0}&&2&6 &&\, 1 & 3 &&\, 2 \\
\cline{4-5}\cline{10-10}
&&&&   \textbf{0} &&  1 & 2 &&\, 6 &&\, 2 \\
\cline{7-8}\cline{12-12}
&&&&&&&           \textbf{1} &&  6 &&\, 3 &&\, 2 \\
\cline{10-10}\cline{14-14}
&&&&&&&&&                \textbf{0}&&\, 2 &&\, \textbf{1} \\
\cline{12-12}
&&&&&&&&&&&                     \textbf{1} \\
\end{array}$} &
\makecell{
$\arraycolsep=0.05em
\begin{array}{r@{\,}r|rr}
\textbf{0} &&\, 16 \\
\cline{1-3}
\textbf{0} &&\, 32 \\
\cline{1-3}
\textbf{0} &&\, 64 \\
 \cline{1-3}
\textbf{1} &&\, 28 \\
 \cline{1-3}
\textbf{0} &&\, 56 \\
 \cline{1-3}
\textbf{1} &&\, 12 \\
\end{array}$}
\end{tabular}
#+END_center

Из чего получаем, что 52.16_10 \approx *110100.00101_2*

** Задание 5
*** Задание
|---+----+-------+----+---|
| # | #  | A     |  B | C |
| / | <> | <     |    | > |
|---+----+-------+----+---|
| # | 27 | 38.64 | 16 | 2 |
|---+----+-------+----+---|

*** Решение
Найти: 38.64_16 = ?_2
#+BEGIN_center
$\arraycolsep=0.05em
\begin{array}{rrrrcrrrrrr}
3  &&    8 && . &&    6 &&    4_{16} && = \\
11 && 1000 && . && 0110 && 0100_2 \\
\end{array}$
#+END_center

Из чего получаем, что 38.64_16 = *111000.011001_2* \approx *111000.011_2*

** Задание 6
*** Задание
|---+----+-------+---+---|
| # | #  | A     | B | C |
| / | <> | <     |   | > |
|---+----+-------+---+---|
| # | 27 | 73.14 | 8 | 2 |
|---+----+-------+---+---|

*** Решение
Найти: 73.14_8 = ?_2
#+BEGIN_center
$\arraycolsep=0.05em
\begin{array}{rrrrcrrrrrr}
  7 &&   3 && . &&   1 &&   4_8 && = \\
111 && 011 && . && 001 && 100_2 \\
\end{array}$
#+END_center

Из чего получаем, что 73.14_8 = *111011.0011_2*

** Задание 7
*** Задание
|---+----+----------+---+----|
| # | #  | A        | B | C  |
| / | <> | <        |   | >  |
|---+----+----------+---+----|
| # | 27 | 0.001001 | 2 | 16 |
|---+----+----------+---+----|

*** Решение
Найти: 0.001001_2 = ?_16
#+BEGIN_center
$\arraycolsep=0.05em
\begin{array}{rrcrrrrrr}
0 && . && 0010 && 0100_2 && = \\
0 && . &&    2 &&    4_{16} \\
\end{array}$
#+END_center

Из чего получаем, что 0.001001_2 = *0.24_16*

** Задание 8
*** Задание
|---+----+----------+---+----|
| # | #  | A        | B | C  |
| / | <> | <        |   | >  |
|---+----+----------+---+----|
| # | 27 | 0.011001 | 2 | 10 |
|---+----+----------+---+----|

*** Решение
Найти: 0.011001_2 = ?_10
#+BEGIn_center
$\begin{array}{lcl}
\overset{0}{0}.\overset{-1}{1}\overset{-2}{1}\overset{-3}{0}\overset{-4}{0}\overset{-5}{1}
& = & 0 * 2^0 + 0 * 2^{-1} + 1 * 2^{-2} + 1 * 2^{-3} + 0 * 2^{-4} + 0 * 2^{-5} + 1 * 2^{-6} \\
& = & 0.25 + 0.125 + 0.015625 = 0.390625_{10}
\end{array}$
#+END_center

Из чего получаем, что 0.011001_2 = *0.390625_10* \approx *0.39063_10*

** Задание 9
*** Задание
|---+----+-------+----+----|
| # | #  | A     |  B | C  |
| / | <> | <     |    | >  |
|---+----+-------+----+----|
| # | 27 | 1F.1E | 16 | 10 |
|---+----+-------+----+----|

*** Решение
Найти: 1F.1E_16 = ?_10
#+BEGIN_center
$\begin{array}{lcl}
\overset{1}{1}\overset{0}{F}.\overset{-1}{1}\overset{-2}{E}
& = & 1 * 16^1 + F * 16^0 + 1 * 16^{-1} + E * 16^{-2} \\
& = & 16 + 15 + 0.625 + 0.0546875 = 31.1171875_{10}
\end{array}$
#+END_center

Из чего получаем, что 1F.1E_16 = *31.1171875_10* \approx *31.11719_10*

** Задание 10
*** Задание
|---+----+----+----+-----|
| # | #  | A  |  B | C   |
| / | <> | <  |    | >   |
|---+----+----+----+-----|
| # | 27 | 75 | 10 | Фиб |
|---+----+----+----+-----|

*** Решение
Найти: 75_10 = ?_Фиб \\
Фибоначчи: $\{\overset{0}{1}, \overset{1}{2}, \overset{2}{3}, \overset{3}{5}, \overset{4}{8},
\overset{5}{13}, \overset{6}{21}, \overset{7}{34}, \overset{8}{55}, \overset{9}{89}\}$ \\
#+BEGIN_center
75_10 = 55 + 13 + 5 + 2 = 100101010_Фиб
#+END_center

Из чего получаем, что 72_10 = *100101010_Фиб*

** Задание 11
*** Задание
|---+----+-------------------------+----+----|
| # | #  | A                       | B  | C  |
| / | <> | <                       |    | >  |
|---+----+-------------------------+----+----|
| # | 27 | $33\overline{2}00$      | 7C | 10 |
|---+----+-------------------------+----+----|

*** Решение
Найти: $33\overline{2}00_{7C} = ?_{10}$ \\
#+BEGIN_center
$\begin{array}{lcl}
\overset{4}{3}\overset{3}{3}\overset{\underline{2}}{2}\overset{1}{0}\overset{0}{0}_{7C}
& = & 3 * 7^4 + 3 * 7^3 + (-2) * 7^2 + 0 * 7^1 + 0 * 7^0 \\
& = & 7203 + 1029 - 686 + 0 + 0 = 7546_{10}
\end{array}$
#+END_center

Из чего получаем, что $33\overline{2}00_{7C}$ = *7546_{10}*

** Результаты
*** Таблица ответов
 | / | <> | <>             |
 |---+----+----------------|
 | # |  # | Ответ          |
 |---+----+----------------|
 | # |  1 | 37638_9        |
 |---+----+----------------|
 | # |  2 | 2439_10        |
 |---+----+----------------|
 | # |  3 | 1344230_5      |
 |---+----+----------------|
 | # |  4 | 110100.00101_2 |
 |---+----+----------------|
 | # |  5 | 111000.011_2   |
 |---+----+----------------|
 | # |  6 | 111011.0011_2  |
 |---+----+----------------|
 | # |  7 | 0.24_16        |
 |---+----+----------------|
 | # |  8 | 0.39063_10     |
 |---+----+----------------|
 | # |  9 | 0.31.11719_10  |
 |---+----+----------------|
 | # | 10 | 100101010_Фиб  |
 |---+----+----------------|
 | # | 11 | 7546_10        |
 |---+----+----------------|

*** Вывод
 В ходе этой лабораторной работы я вспомнил как работать с различными системами
 счисления и алгоритмами для перевода чисел из одной СС в другую, а так же
 укрепил познакомился с СС на базе чисел Фибоначчи, факториальной СС и
 СС с отрицательными основаниями или числами.
